package valkyrie.driver.mysql;

import valkyrie.driver.suggestion.SqlStandardSuggestions;
import valkyrie.driver.suggestion.Suggestion;

import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * MySQL 关键字
 *
 * @author Luo Tiansheng
 * @since 2026/5/7
 */
public class MySQLSuggestions
{
        public static final Set<Suggestion> VALUES;

        static {
                Set<Suggestion> values = new LinkedHashSet<>();

                Collections.addAll(values,
                        // 存储过程与函数
                        Suggestion.ofKeyword("ACCESSIBLE"),
                        Suggestion.ofFunction("AGAINST"),
                        Suggestion.ofKeyword("ASENSITIVE"),
                        Suggestion.ofKeyword("CONDITION"),
                        Suggestion.ofKeyword("CONTINUE"),
                        Suggestion.ofKeyword("CURSOR"),
                        Suggestion.ofKeyword("DETERMINISTIC"),
                        Suggestion.ofKeyword("EACH"),
                        Suggestion.ofKeyword("ELSEIF"),
                        Suggestion.ofKeyword("EXIT"),
                        Suggestion.ofKeyword("FETCH"),
                        Suggestion.ofKeyword("GOTO"),
                        Suggestion.ofKeyword("INOUT"),
                        Suggestion.ofKeyword("ITERATE"),
                        Suggestion.ofKeyword("LEAVE"),
                        Suggestion.ofKeyword("LOOP"),
                        Suggestion.ofKeyword("MODIFIES"),
                        Suggestion.ofKeyword("PREPARE"),
                        Suggestion.ofKeyword("READS"),
                        Suggestion.ofKeyword("REPEAT"),
                        Suggestion.ofKeyword("REQUIRE"),
                        Suggestion.ofKeyword("RETURN"),
                        Suggestion.ofKeyword("SCHEMAS"),
                        Suggestion.ofKeyword("SENSITIVE"),
                        Suggestion.ofKeyword("SPECIFIC"),
                        Suggestion.ofKeyword("SQLEXCEPTION"),
                        Suggestion.ofKeyword("SQLSTATE"),
                        Suggestion.ofKeyword("SQLWARNING"),
                        Suggestion.ofKeyword("UNDO"),
                        Suggestion.ofKeyword("WHILE"),
                        Suggestion.ofFunction("FROM_BASE64"),
                        // 全文搜索
                        Suggestion.ofKeyword("FULLTEXT"),
                        Suggestion.ofKeyword("MATCH"),
                        // 索引
                        Suggestion.ofKeyword("KEY"),
                        Suggestion.ofKeyword("KEYS"),
                        Suggestion.ofKeyword("SPATIAL"),
                        Suggestion.ofKeyword("USING"),
                        Suggestion.ofKeyword("BTREE"),
                        Suggestion.ofKeyword("HASH"),
                        // 字符串类型与函数
                        Suggestion.ofFunction("ASCII"),
                        Suggestion.ofKeyword("BINARY"),
                        Suggestion.ofKeyword("BLOB"),
                        Suggestion.ofKeyword("CHARACTER"),
                        Suggestion.ofKeyword("COLLATE"),
                        Suggestion.ofKeyword("VARCHAR"),
                        Suggestion.ofKeyword("VARYING"),
                        Suggestion.ofKeyword("LINEAR"),
                        // 数值类型
                        Suggestion.ofKeyword("BIT"),
                        Suggestion.ofKeyword("INT"),
                        Suggestion.ofKeyword("INTEGER"),
                        Suggestion.ofKeyword("MEDIUMINT"),
                        Suggestion.ofKeyword("SMALLINT"),
                        Suggestion.ofKeyword("TINYINT"),
                        Suggestion.ofKeyword("FLOAT"),
                        Suggestion.ofKeyword("DOUBLE"),
                        Suggestion.ofKeyword("REAL"),
                        Suggestion.ofKeyword("NUMERIC"),
                        Suggestion.ofKeyword("DECIMAL"),
                        Suggestion.ofKeyword("PRECISION"),
                        Suggestion.ofKeyword("UNSIGNED"),
                        Suggestion.ofKeyword("ZEROFILL"),
                        Suggestion.ofKeyword("MAXVALUE"),
                        Suggestion.ofKeyword("MINVALUE"),
                        // 存储与加载
                        Suggestion.ofKeyword("LINES"),
                        Suggestion.ofKeyword("TERMINATED"),
                        Suggestion.ofKeyword("ENCLOSED"),
                        Suggestion.ofKeyword("ESCAPED"),
                        Suggestion.ofKeyword("LOAD"),
                        Suggestion.ofKeyword("INFILE"),
                        Suggestion.ofKeyword("OUTFILE"),
                        Suggestion.ofKeyword("DELIMITER"),
                        // 时间类型
                        Suggestion.ofKeyword("TIME"),
                        Suggestion.ofKeyword("TIMESTAMP"),
                        Suggestion.ofKeyword("INTERVAL"),
                        Suggestion.ofKeyword("DAY_HOUR"),
                        Suggestion.ofKeyword("DAY_MICROSECOND"),
                        Suggestion.ofKeyword("DAY_MINUTE"),
                        Suggestion.ofKeyword("DAY_SECOND"),
                        Suggestion.ofKeyword("HOUR_MICROSECOND"),
                        Suggestion.ofKeyword("HOUR_MINUTE"),
                        Suggestion.ofKeyword("HOUR_SECOND"),
                        Suggestion.ofKeyword("MINUTE_MICROSECOND"),
                        Suggestion.ofKeyword("SECOND_MICROSECOND"),
                        Suggestion.ofKeyword("YEAR_MONTH"),
                        // 排序与分区
                        Suggestion.ofKeyword("PARTITION"),
                        Suggestion.ofKeyword("PARTITIONS"),
                        Suggestion.ofKeyword("SUBPARTITION"),
                        Suggestion.ofKeyword("SUBPARTITIONS"),
                        Suggestion.ofKeyword("RANGE"),
                        Suggestion.ofKeyword("LIST"),
                        Suggestion.ofKeyword("COLUMNS"),
                        Suggestion.ofKeyword("ALGORITHM"),
                        // 事务与锁
                        Suggestion.ofKeyword("LOCK"),
                        Suggestion.ofKeyword("UNLOCK"),
                        Suggestion.ofKeyword("READ"),
                        Suggestion.ofKeyword("WRITE"),
                        Suggestion.ofKeyword("LOCAL"),
                        Suggestion.ofKeyword("LOW_PRIORITY"),
                        Suggestion.ofKeyword("HIGH_PRIORITY"),
                        Suggestion.ofKeyword("DELAYED"),
                        Suggestion.ofKeyword("NO_WRITE_TO_BINLOG"),
                        Suggestion.ofKeyword("BINLOG"),
                        // 用户与权限
                        Suggestion.ofKeyword("USER"),
                        Suggestion.ofKeyword("ROLE"),
                        Suggestion.ofKeyword("PASSWORD"),
                        Suggestion.ofKeyword("GRANT"),
                        Suggestion.ofKeyword("REVOKE"),
                        Suggestion.ofKeyword("ssl"),
                        Suggestion.ofKeyword("cipher"),
                        Suggestion.ofKeyword("issuer"),
                        Suggestion.ofKeyword("subject"),
                        // 服务器选项
                        Suggestion.ofKeyword("AUTO"),
                        Suggestion.ofKeyword("AUTO_INCREMENT"),
                        Suggestion.ofKeyword("AVG_ROW_LENGTH"),
                        Suggestion.ofKeyword("BACKUP"),
                        Suggestion.ofKeyword("CACHE"),
                        Suggestion.ofKeyword("CHECKSUM"),
                        Suggestion.ofKeyword("COMMENT"),
                        Suggestion.ofKeyword("COMPRESS"),
                        Suggestion.ofKeyword("CONNECTION"),
                        Suggestion.ofKeyword("DATA"),
                        Suggestion.ofKeyword("DIRECTORY"),
                        Suggestion.ofKeyword("DISK"),
                        Suggestion.ofKeyword("DO"),
                        Suggestion.ofKeyword("DUMPFILE"),
                        Suggestion.ofKeyword("ENCRYPTION"),
                        Suggestion.ofKeyword("ENGINE"),
                        Suggestion.ofKeyword("FIRST"),
                        Suggestion.ofKeyword("FIXED"),
                        Suggestion.ofKeyword("FLUSH"),
                        Suggestion.ofKeyword("FULL"),
                        Suggestion.ofKeyword("GLOBAL"),
                        Suggestion.ofKeyword("IGNORE"),
                        Suggestion.ofKeyword("INDEX"),
                        Suggestion.ofKeyword("INSERT_METHOD"),
                        Suggestion.ofKeyword("KEY_BLOCK_SIZE"),
                        Suggestion.ofKeyword("LAST"),
                        Suggestion.ofKeyword("MAX_ROWS"),
                        Suggestion.ofKeyword("MEMORY"),
                        Suggestion.ofKeyword("MIN_ROWS"),
                        Suggestion.ofKeyword("MODIFY"),
                        Suggestion.ofKeyword("MRG_MYISAM"),
                        Suggestion.ofKeyword("PACK_KEYS"),
                        Suggestion.ofKeyword("PERSISTENT"),
                        Suggestion.ofKeyword("PROCEDURE"),
                        Suggestion.ofKeyword("QUICK"),
                        Suggestion.ofKeyword("RAID_0"),
                        Suggestion.ofKeyword("RAID_1"),
                        Suggestion.ofKeyword("RAID_5"),
                        Suggestion.ofKeyword("REBUILD"),
                        Suggestion.ofKeyword("REPAIR"),
                        Suggestion.ofKeyword("REPLICATE"),
                        Suggestion.ofKeyword("RESTORE"),
                        Suggestion.ofKeyword("ROLLUP"),
                        Suggestion.ofKeyword("ROW_FORMAT"),
                        Suggestion.ofKeyword("SLOW"),
                        Suggestion.ofKeyword("STORAGE"),
                        Suggestion.ofKeyword("UNIQUE"),
                        Suggestion.ofKeyword("USE_FRM"),
                        Suggestion.ofKeyword("VIRTUAL"),
                        // 字符集与校验规则
                        Suggestion.ofKeyword("CHARSET"),
                        Suggestion.ofKeyword("COLLATION"),
                        Suggestion.ofKeyword("UPPERCASE"),
                        Suggestion.ofKeyword("UNICODE"),
                        Suggestion.ofKeyword("UTF8"),
                        Suggestion.ofKeyword("UTF8MB4"),
                        Suggestion.ofKeyword("LATIN1"),
                        // JSON 相关
                        Suggestion.ofKeyword("JSON"),
                        Suggestion.ofFunction("JSON_ARRAY"),
                        Suggestion.ofFunction("JSON_OBJECT"),
                        Suggestion.ofFunction("JSON_EXTRACT"),
                        Suggestion.ofFunction("JSON_SET"),
                        Suggestion.ofFunction("JSON_INSERT"),
                        Suggestion.ofFunction("JSON_REPLACE"),
                        Suggestion.ofFunction("JSON_REMOVE"),
                        Suggestion.ofFunction("JSON_MERGE"),
                        Suggestion.ofFunction("JSON_MERGE_PATCH"),
                        Suggestion.ofFunction("JSON_MERGE_PRESERVE"),
                        Suggestion.ofFunction("JSON_QUOTE"),
                        Suggestion.ofFunction("JSON_UNQUOTE"),
                        Suggestion.ofFunction("JSON_ARRAY_APPEND"),
                        Suggestion.ofFunction("JSON_ARRAY_INSERT"),
                        Suggestion.ofFunction("JSON_CONTAINS"),
                        Suggestion.ofFunction("JSON_CONTAINS_PATH"),
                        Suggestion.ofFunction("JSON_DEPTH"),
                        Suggestion.ofFunction("JSON_DOCUMENT"),
                        Suggestion.ofFunction("JSON_EACH"),
                        Suggestion.ofFunction("JSON_EXISTS"),
                        Suggestion.ofFunction("JSON_GET"),
                        Suggestion.ofFunction("JSON_HAS"),
                        Suggestion.ofFunction("JSON_KEYS"),
                        Suggestion.ofFunction("JSON_LENGTH"),
                        Suggestion.ofFunction("JSON_OVERLAPS"),
                        Suggestion.ofFunction("JSON_PRETTY"),
                        Suggestion.ofFunction("JSON_QUERY"),
                        Suggestion.ofFunction("JSON_SCHEMA"),
                        Suggestion.ofFunction("JSON_SEARCH"),
                        Suggestion.ofFunction("JSON_STORAGE_FREE"),
                        Suggestion.ofFunction("JSON_STORAGE_SIZE"),
                        Suggestion.ofFunction("JSON_TABLE"),
                        Suggestion.ofFunction("JSON_TYPE"),
                        Suggestion.ofFunction("JSON_VALID"),
                        Suggestion.ofFunction("JSON_VALUE"),
                        // 表达式与操作符
                        Suggestion.ofOperator("REGEXP"),
                        Suggestion.ofOperator("RLIKE"),
                        Suggestion.ofFunction("SOUNDS"),
                        Suggestion.ofOperator("XOR"),
                        Suggestion.ofOperator("DIV"),
                        Suggestion.ofKeyword("DUAL"),
                        Suggestion.ofKeyword("BOTH"),
                        Suggestion.ofKeyword("LEADING"),
                        Suggestion.ofKeyword("TRAILING"),
                        // 优化与分析
                        Suggestion.ofKeyword("ANALYZE"),
                        Suggestion.ofKeyword("FORCE"),
                        Suggestion.ofKeyword("IGNORE"),
                        Suggestion.ofFunction("OPTIMIZE"),
                        Suggestion.ofKeyword("STRAIGHT_JOIN"),
                        Suggestion.ofKeyword("SQL_CACHE"),
                        Suggestion.ofKeyword("SQL_NO_CACHE"),
                        Suggestion.ofKeyword("SQL_CALC_FOUND_ROWS"),
                        Suggestion.ofKeyword("SQL_SMALL_RESULT"),
                        Suggestion.ofKeyword("SQL_BIG_RESULT"),
                        Suggestion.ofKeyword("SQL_BUFFER_RESULT"),
                        Suggestion.ofKeyword("SQL_SAFE_UPDATES"),
                        Suggestion.ofKeyword("FUNCTION"),
                        // 复制
                        Suggestion.ofKeyword("MASTER"),
                        Suggestion.ofKeyword("SLAVE"),
                        Suggestion.ofKeyword("REPLICATION"),
                        Suggestion.ofKeyword("SOURCE"),
                        Suggestion.ofKeyword("REPLICA"),
                        Suggestion.ofKeyword("GTID"),
                        Suggestion.ofKeyword("SERIALIZABLE"),
                        Suggestion.ofKeyword("CHANNEL"),
                        Suggestion.ofKeyword("DOCUMENT"),
                        Suggestion.ofKeyword("EVENT"),
                        Suggestion.ofKeyword("EVENTS"),
                        Suggestion.ofKeyword("FILE"),
                        Suggestion.ofKeyword("GENERAL"),
                        Suggestion.ofKeyword("HOSTS"),
                        Suggestion.ofKeyword("LOGS"),
                        Suggestion.ofKeyword("MASTER_LOG_FILE"),
                        Suggestion.ofKeyword("MASTER_LOG_POS"),
                        Suggestion.ofFunction("MASTER_POS_WAIT"),
                        Suggestion.ofKeyword("RELAY_LOG_FILE"),
                        Suggestion.ofKeyword("RELAY_LOG_POS"),
                        Suggestion.ofKeyword("RELAY_THREAD"),
                        Suggestion.ofKeyword("SOURCE_LOG_FILE"),
                        Suggestion.ofKeyword("SOURCE_LOG_POS"),
                        // 会话
                        Suggestion.ofKeyword("SESSION"),
                        Suggestion.ofKeyword("SESSION_USER"),
                        Suggestion.ofKeyword("SYSTEM_USER"),
                        Suggestion.ofKeyword("CURRENT_USER"),
                        Suggestion.ofKeyword("CURRENT_ROLE"),
                        Suggestion.ofFunction("FOUND_ROWS"),
                        Suggestion.ofFunction("LAST_INSERT_ID"),
                        Suggestion.ofFunction("ROW_COUNT"),
                        Suggestion.ofFunction("VERSION"),
                        Suggestion.ofKeyword("DATABASE"),
                        Suggestion.ofKeyword("SCHEMA"),
                        // 窗口函数 (MySQL 8.0+)
                        Suggestion.ofKeyword("OVER"),
                        Suggestion.ofKeyword("WINDOW"),
                        Suggestion.ofKeyword("UNBOUNDED"),
                        Suggestion.ofKeyword("PRECEDING"),
                        Suggestion.ofKeyword("FOLLOWING"),
                        Suggestion.ofKeyword("CURRENT ROW"),
                        Suggestion.ofKeyword("EXCLUDE"),
                        Suggestion.ofKeyword("NO OTHERS"),
                        Suggestion.ofKeyword("TIES"),
                        Suggestion.ofKeyword("GROUPS"),
                        // 其他
                        Suggestion.ofKeyword("ALWAYS"),
                        Suggestion.ofKeyword("CHANGE"),
                        Suggestion.ofKeyword("CHAR"),
                        Suggestion.ofKeyword("DISTINCTROW"),
                        Suggestion.ofKeyword("FLOAT4"),
                        Suggestion.ofKeyword("FLOAT8"),
                        Suggestion.ofKeyword("GET"),
                        Suggestion.ofKeyword("SET"),
                        Suggestion.ofKeyword("KILL"),
                        Suggestion.ofKeyword("OPTION"),
                        Suggestion.ofKeyword("OPTIONALLY"),
                        Suggestion.ofKeyword("PURGE"),
                        Suggestion.ofKeyword("RANK"),
                        Suggestion.ofKeyword("RENAM"),
                        Suggestion.ofKeyword("REOKE"),
                        Suggestion.ofKeyword("ROW"),
                        Suggestion.ofKeyword("ROWS"),
                        Suggestion.ofKeyword("SHOW"),
                        Suggestion.ofKeyword("START"),
                        Suggestion.ofKeyword("STOP"),
                        Suggestion.ofKeyword("TRUNCATE"),
                        Suggestion.ofKeyword("UPDATE"),
                        Suggestion.ofKeyword("SIGNAL"),
                        Suggestion.ofKeyword("RESIGNAL"),
                        Suggestion.ofKeyword("GET_DIAGNOSTICS"),
                        Suggestion.ofKeyword("CONDITION_HANDLER"),
                        Suggestion.ofKeyword("START TRANSACTION"),
                        Suggestion.ofKeyword("COMMIT"),
                        Suggestion.ofKeyword("ROLLBACK"),
                        Suggestion.ofKeyword("SAVEPOINT"),
                        // 约束
                        Suggestion.ofKeyword("RESTRICT"),
                        Suggestion.ofKeyword("CASCADE"),
                        Suggestion.ofKeyword("SET NULL"),
                        Suggestion.ofKeyword("NO ACTION"),
                        Suggestion.ofKeyword("SET DEFAULT"),
                        // 虚拟列与生成列
                        Suggestion.ofKeyword("GENERATED"),
                        Suggestion.ofKeyword("STORED"),
                        // 公共表表达式 (CTE)
                        Suggestion.ofKeyword("RECURSIVE")
                );

                values.addAll(SqlStandardSuggestions.VALUES);
                VALUES = Collections.unmodifiableSet(values);
        }

        private MySQLSuggestions()
        {
                /* DO NOTHING... */
        }
}
